// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRWHrIyGdXmEDx6yj4IwiDWj9vS1VIMI',
    appId: '1:513614089942:web:6c9293b7dcd52168ed8377',
    messagingSenderId: '513614089942',
    projectId: 'topup-shop-e27a7',
    authDomain: 'topup-shop-e27a7.firebaseapp.com',
    storageBucket: 'topup-shop-e27a7.appspot.com',
    measurementId: 'G-RJZWW9EV85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrWelEz_eqnIC4kqMH9-DQU4P6WnHmjTk',
    appId: '1:513614089942:android:47ecc9b8514a7cb9ed8377',
    messagingSenderId: '513614089942',
    projectId: 'topup-shop-e27a7',
    storageBucket: 'topup-shop-e27a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4OdIkXFDdhxS1S-RwVkOdUPtnkWboorw',
    appId: '1:513614089942:ios:246a855f581952cfed8377',
    messagingSenderId: '513614089942',
    projectId: 'topup-shop-e27a7',
    storageBucket: 'topup-shop-e27a7.appspot.com',
    iosClientId: '513614089942-uk04hvs6knmamkgo6kb41he8n86527sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.topupShop',
  );
}
